### ISSUE TITLE
File extensions does not stick to conventions

### ISSUE THREAD

**Issue by ziobron** [coders-school/kurs_cpp_podstawowy#1]
From: https://github.com/lefticus/cppbestpractices/blob/master/03-Style.md

### Use .hpp and .cpp for Your File Extensions
> Ultimately this is a matter of preference, but .hpp and .cpp are widely recognized by various editors and tools. So the choice is pragmatic. Specifically, Visual Studio only automatically recognizes .cpp and .cxx for C++ files, and Vim doesn't necessarily recognize .cc as a C++ file.

> One particularly large project (OpenStudio) uses .hpp and .cpp for user-generated files and .hxx and .cxx for tool-generated files. Both are well recognized and having the distinction is helpful.

Please use cpp and hpp instead of cc and hh :)

**Comment by nauka-programowania-MA** [comment]
Fixed
