### ISSUE TITLE
Invisible code in the std::map lesson

### ISSUE THREAD

**Issue by anraf1001** [coders-school/kurs_cpp_podstawowy#120]
In the example code, `pair.first` and `pair.second` are invisible:
![Opera Zrzut ekranu_2020-05-21_082723_coders school](https://user-images.githubusercontent.com/28186871/82530400-8252db80-9b3d-11ea-9197-862fed31c966.png)

**Comment by ziobron** [comment]
Thanks. Fixed now.
<img width="559" alt="Zrzut ekranu 2020-05-25 o 01 16 46" src="https://user-images.githubusercontent.com/4595135/82767138-6bee9d80-9e25-11ea-901a-b16efdc9efaf.png">
