### ISSUE TITLE
Postawy#2 Range based for loop - Strange sentence on presentation 

### ISSUE THREAD

**Issue by niemarcin** [coders-school/kurs_cpp_podstawowy#148]
In presentation kurs_cpp_podstawowy/module2/presentation_range_for.md

Sentence:
> Kompilator może sam **go** wygenerować powyższy kod, jeśli użyjemy poniższego zapisu.

I'm not sure but something is wrong here. Maybe "go" word ;)

**Comment by ziobron** [comment]
Please create a PR with a fix :)

**Comment by niemarcin** [comment]
Done
