### ISSUE TITLE
Module 1 presentation: size of bool type - exactly 1byte / at least 1byte

### ISSUE THREAD

**Issue by niemarcin** [coders-school/kurs_cpp_podstawowy#272]
In presentation about data types from module 1: https://github.com/coders-school/kurs_cpp_podstawowy/blob/master/module1/presentation_types.md

in section about bool type there is an information "_Rozmiar: co najmniej 1 bajt_", but later in this presentation, in section about char, there is an information "_Rozmiar typów logicznych i znakowych to zawsze 1 bajt._"

So the question is - does bool always have exactly 1byte or at least 1byte?

https://en.cppreference.com/w/cpp/language/types says: 
_Boolean type
bool - type, capable of holding one of the two values: true or false. The value of sizeof(bool) is implementation defined and might differ from 1._

**Comment by ziobron** [comment]
It's _usually_ 1 byte, but as cppreference says it may be different. Do you want to create a PR that fixes it?

**Comment by niemarcin** [comment]
Sure, I will do this ;)

**Comment by niemarcin** [comment]
Done
