### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by kyrtaq** [coders-school/kurs_cpp_podstawowy#286]
the ideas were also proposed by @niemarcin and @krzysieks and @neobauer
-the notifications should be more minimalistic (@niemarcin proposal is awesome imo)
-the notifications should disappear after some seconds, imo 3 seconds it's enough
-maybe the notifications should come in packs? for example when you get 3 points you get one notification telling you that you've achieved 3 points for (example) code review

**Comment by niemarcin** [comment]
Here is an example of minimalistic notification: 
![image](https://user-images.githubusercontent.com/19634288/84014490-b0784e00-a97a-11ea-8cca-c35a74603b77.png)

**Comment by kyrtaq** [comment]
@niemarcin what do you think about color-indicating particular notifications? so for example when you see blue text you immediately know that it`s for Pull Request

**Comment by niemarcin** [comment]
@kyrtaq I don't know.  The question is how many colors will be there to remember :D

**Comment by kyrtaq** [comment]
@niemarcin maybe if it only color the 'Pull Request' or 'Code Review' (or some other achievement) then it would be more aesthetic and more readable, imo :)

**Comment by niemarcin** [comment]
It looks like some of the notifications actually are already in this minimalistic style. Only the date and notification text are line-swapped in comparison to what I proposed. But looks fine for me. 

![image](https://user-images.githubusercontent.com/19634288/84208518-38ae3e80-aab4-11ea-9937-4d9305d67976.png)

Not sure if it's new or it was already like that for some of notifications.

**Comment by ziobron** [comment]
The title of this issue is not meaningful at all. And it should be raised in `site` repo :)
Let me close this issue. If you want colors on notifications - please raise a separate issue in site repo :) Notifications for points are already in a proposed "minimalistic" way :)
