### ISSUE TITLE
Missing file for adding colabolator

### ISSUE THREAD

**Issue by WBigaj** [coders-school/kurs_cpp_podstawowy#332]
![Error 1](https://user-images.githubusercontent.com/22654594/93002198-78fade00-f535-11ea-9c7f-7e08909eeb59.png)
![Error 2](https://user-images.githubusercontent.com/22654594/93002199-79937480-f535-11ea-9cb2-e735f10e255f.png)

**Comment by ziobron** [comment]
Images will not work on our platform. After this edition we will fix all problems with images. Let me close it for now.
