### ISSUE TITLE
What is "Tablica w pamięci"

### ISSUE THREAD

**Issue by WBigaj** [coders-school/kurs_cpp_podstawowy#333]
![What is this](https://user-images.githubusercontent.com/22654594/93016916-eefa5600-f5c4-11ea-8a41-5def48da85fb.png)

And why it is directing to the beginning of array presentation?

**Comment by ziobron** [comment]
It's image that is not handled by the platform. We cannot solve it now. It will require adding a library that parse markdown. Now we use GitHub parser for it and it generates relative paths to images and that's why it doesn't work. 
Closing the issue.
